version: '3.4'

services:
  distcachedb:
    image: redis:alpine

  tasksdb:
    image: mongo

  portainer:
    image: portainer/portainer-ce

  userdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
       image: rabbitmq:3-management-alpine

  seq:
    image: datalust/seq:latest


  authentication.api:
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
      context: .
      dockerfile: Services/Authentication/Authentication.API/Dockerfile

  localization.grpc:
    image: ${DOCKER_REGISTRY-}localizationgrpc
    build:
      context: .
      dockerfile: Services/Localization/Localization.Grpc/Dockerfile

  tasks.api:
    image: ${DOCKER_REGISTRY-}tasksapi
    build:
      context: .
      dockerfile: Services/Tasks/Tasks.API/Dockerfile

  announcement.api:
    image: ${DOCKER_REGISTRY-}announcementapi
    build:
      context: .
      dockerfile: Services/Announcement/Announcement.API/Dockerfile

  tasks.job:
    image: ${DOCKER_REGISTRY-}tasksjob
    build:
      context: .
      dockerfile: Services/Tasks/Tasks.Job/Dockerfile

  pomodoros.api:
    image: ${DOCKER_REGISTRY-}pomodorosapi
    build:
      context: .
      dockerfile: Services/Pomodoros/Pomodoros.API/Dockerfile

  apigw:
    image: ${DOCKER_REGISTRY-}apigw
    build:
      context: .
      dockerfile: ApiGateway/ApiGw/Dockerfile

  eventbus.job:
    image: ${DOCKER_REGISTRY-}eventbusjob
    build:
      context: .
      dockerfile: MessagingQueue/MessagingQueue.Job/Dockerfile

volumes:
  portainer_data:    
  sql_data:
  mongo_data:






