version: '3.4'

services:


  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data




  authentication.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9500:80"