version: '3.4'

services:
  tasksdb:
    image: mongo

  portainer:
    image: portainer/portainer-ce

  userdb:
    image: mcr.microsoft.com/mssql/server:2017-latest


  authentication.api:
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
      context: .
      dockerfile: Services/Authentication/Authentication.API/Dockerfile

  localization.grpc:
    image: ${DOCKER_REGISTRY-}localizationgrpc
    build:
      context: .
      dockerfile: Services/Localization/Localization.Grpc/Dockerfile

  tasks.api:
    image: ${DOCKER_REGISTRY-}tasksapi
    build:
      context: .
      dockerfile: Services/Tasks/Tasks.API/Dockerfile

volumes:
  portainer_data:    
  sql_data:
  mongo_data:

