version: '3.4'

services:

  portainer:
    image: portainer/portainer-ce

  userdb:
    image: mcr.microsoft.com/mssql/server:2017-latest


  authentication.api:
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
      context: .
      dockerfile: Services/Authentication/Authentication.API/Dockerfile

volumes:
  portainer_data:    
  sql_data: