version: '3.4'

services:

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  userdb:
    container_name: user
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets


  authentication.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:UserDBQueryConnection=Server=userdb;Database=UsersDb;User Id=sa;Password=SwN12345678;ApplicationIntent=ReadOnly;"
      - "DatabaseSettings:UserDBConnection=Server=userdb;Database=UsersDb;User Id=sa;Password=SwN12345678;"
    depends_on:
      - userdb
    ports:
      - "5700:80"
  localization.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
